name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update version in package.json
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          # Update version in package.json
          npm version $VERSION --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: meteogram-card.js
          tag_name: ${{ github.ref_name }}
